### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by aman-112** [Muhammad-Ahsan-Rasheed/Chegg-Discord-Bot#1]
Chegg link received!!
list index out of range

This is what I got after running the bot and installing the packages.
<img width="533" alt="Capture" src="https://user-images.githubusercontent.com/86217022/128520012-e2f53e97-acc5-45bd-8fe7-ab230a7a2027.PNG">

**Comment by AliAdnanc7** [comment]
> Chegg link received!!
> list index out of range
> 
> This is what I got after running the bot and installing the packages.
> <img alt="Capture" width="533" src="https://user-images.githubusercontent.com/86217022/128520012-e2f53e97-acc5-45bd-8fe7-ab230a7a2027.PNG">
There is more than one reason for this problem.... Either because of the inability to open a link or access token that has expired


requests library
Not always able to pull uuid
I use another library that is able to open more links

import urllib3
http = urllib3.PoolManager()

And to specify the uuid use the re . library
import re
mm=str(r.data.decode("utf-8"))
w = re.findall('''"questionUuid":"\w{8}-\w{4}-\w{4}-\w{4}-\w{12}"'',mm)

**Comment by akaa0** [comment]
> > Chegg link received!!
> > list index out of range
> > This is what I got after running the bot and installing the packages.
> > <img alt="Capture" width="533" src="https://user-images.githubusercontent.com/86217022/128520012-e2f53e97-acc5-45bd-8fe7-ab230a7a2027.PNG">
> > There is more than one reason for this problem.... Either because of the inability to open a link or access token that has expired
> 
> requests library Not always able to pull uuid I use another library that is able to open more links
> 
> import urllib3 http = urllib3.PoolManager()
> 
> And to specify the uuid use the re . library import re mm=str(r.data.decode("utf-8")) w = re.findall('''"questionUuid":"\w{8}-\w{4}-\w{4}-\w{4}-\w{12}"'',mm)

Can explain more about how to fix it?

**Comment by Muhammad-Ahsan-Rasheed** [comment]
You've to first run the **setup.py** file and when you see **successfully login** then run the **main.py** file...

**Comment by Ednn0nd1au** [comment]
Same issue happened here. Link is received but list index out of range. Any solutions please~

@Muhammad-Ahsan-Rasheed @AliAdnanc7 @aman-112

**Comment by Muhammad-Ahsan-Rasheed** [comment]
It happened when the account is not sign in properly. So when I received this issue I just run the setup file sign in and then the error was gone.
