### ISSUE TITLE
Submit your Demo for Feedback purpose

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [Muhammad-Ahsan-Rasheed/Chegg-Discord-Bot#11]
Hi everyone, 
I hope you find this project helpful. I'm conducting a feedback survey so it is requested to all to share the demo of this working project.

@shriekdj @everyone

Looking Forward,

Thanks and Regards,

**Comment by shriekdj** [comment]
I apologize for unable to share the demo of this working project, because I just found the reviewed the code as per bot docs and and not ran the direct tests with Chegg API Keys.
