### ISSUE TITLE
upload Question

### ISSUE THREAD

**Issue by afwdaw** [Muhammad-Ahsan-Rasheed/Chegg-Discord-Bot#3]
We want to upload Questions using the bot.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
I can't understand what you mean by Uploading Question. You can send the Question Link in Discord following by Command given and the Bot will share the Answer right into channel.

**Comment by afwdaw** [comment]
> I can't understand what you mean by Uploading Question. You can send the Question Link in Discord following by Command given and the Bot will share the Answer right into channel.

I mean we want function to upload new Question to chegg
