### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by afwdaw** [Muhammad-Ahsan-Rasheed/Chegg-Discord-Bot#4]
when trying to get this Q `https://www.chegg.com/homework-help/sample-air-occupies-38-l-pressure-12-atm-volume-occupy-66-at-chapter-5-problem-22p-solution-9780072980608-exc`
the bot will return the answer for Problem `#1` so the problemID here have some issue
please fix it @Muhammad-Ahsan-Rasheed

**Comment by Muhammad-Ahsan-Rasheed** [comment]
ProblemID is generated randomly so it is **quite possible that the IDs match**. Furthermore you can check your code, files are saving there.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
ProblemID is generated randomly so it is **quite possible that the IDs match**. Furthermore you can check your code, files are saving there.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
ProblemID is generated randomly so it is **quite possible that the IDs match**. Furthermore you can check your code, files are saving there.

**Comment by afwdaw** [comment]
> ProblemID is generated randomly so it is **quite possible that the IDs match**. Furthermore you can check your code, files are saving there.

No this bug you can try it and there is new bug
in new Question see the answer and see the output 
https://www.chegg.com/homework-help/questions-and-answers/write-data-commentary-graph--chart-shows-global-sales-top-five-mobile-phone-brands-2009-20-q90850809

![image](https://user-images.githubusercontent.com/90502444/147683952-975089e1-26eb-4a22-9e2a-10cf309898ef.png)
