### ISSUE TITLE
List out of range

### ISSUE THREAD

**Issue by Ednn0nd1au** [Muhammad-Ahsan-Rasheed/Chegg-Discord-Bot#9]
Hi there,

Like is received but list out of range, any solutions please! Much appreciated.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/36107555/169665909-6c6c77fb-2128-4e34-94cb-9d6d76bff58d.png">

**Comment by Muhammad-Ahsan-Rasheed** [comment]
Hey it happens when the account is not sign in properly or sign out due to any reason so

Run the setup file and sign in then hopefully error will be resolved.

**Comment by Ednn0nd1au** [comment]
Hi @Muhammad-Ahsan-Rasheed 

Thank you for answering the question.

After re-sigging to the account, the bot is activated. But when send chegg like to the bot, it replied:
Chegg link received!!
Invalid URL '': No scheme supplied. Perhaps you meant http://?


Example:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/36107555/169706435-79e167e9-9fbe-455f-93ad-1e7b55510162.png">

**Comment by Ednn0nd1au** [comment]
Hi again @Muhammad-Ahsan-Rasheed ,

So this time the previous error happened aggain after trying to send links to bot:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/36107555/169706562-52a90566-5f3b-427f-9a90-bbc5d9255ac9.png">

**Comment by Ednn0nd1au** [comment]
Hi @Muhammad-Ahsan-Rasheed ,

Thank you for the reply! I move the code to a computer that used chegg before and the question is solved.

But I got a new one: After receiving the link and the progamme was able to get the answer, but not able to send it with the following error:

'Client' object has no attribute 'send'

Would you please suggest any solutions? Thanks in advance!

**Comment by Ednn0nd1au** [comment]
@Muhammad-Ahsan-Rasheed Hello again, I notice that this code is only available on Mac OS. Every time when I try to open it with Windows or Ubuntu, the error happens. Would you please kindly suggest any solutions on this~

**Comment by Muhammad-Ahsan-Rasheed** [comment]
Hey @Ednn0nd1au did you modify the code? Because this error only happened with you. Furthermore the code is not for Mac OS I developed it on Windows OS.

**Comment by Ednn0nd1au** [comment]
Hey @Muhammad-Ahsan-Rasheed Thank you for answering the question. No I did not change any code from you but it is tricky that this problem will not happen on my MacOS but only on my Windows. Even with the same code copied from Mac, the "list out of range" error still happened. I can make sure that on Windows the chegg is registered with the device.
